trigger:
- master
 
stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      name: default
    steps:
    - script: echo 'Building Docker image...'
      displayName: 'Build Step'
    - script: |
        docker build -t shubhamdev2001/my-portfolio:latest .
      displayName: 'Docker Build'
 
- stage: Deploy
  jobs:
  - job: DeployJob
    pool:
      name: default
    steps:
    - script: |
        docker login -u shubhamdev2001 -p $DOCKER_PASSWORD
      displayName: 'Docker Login'
    - script: |
        docker push shubhamdev2001/my-portfolio:latest
      displayName: 'Docker Push'
    - script: |
        docker pull shubhamdev2001/my-portfolio:latest
      displayName: 'Docker Pull'
    - script: |
        docker run -d -p 8087:80 shubhamdev2001/my-portfolio:latest
      displayName: 'Docker Run'
    - script: |
        docker ps
      displayName: 'Containers Started'   